/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScatterRouteImport } from './routes/scatter'
import { Route as IndexRouteImport } from './routes/index'

const ScatterRoute = ScatterRouteImport.update({
  id: '/scatter',
  path: '/scatter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scatter': typeof ScatterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scatter': typeof ScatterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scatter': typeof ScatterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scatter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scatter'
  id: '__root__' | '/' | '/scatter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScatterRoute: typeof ScatterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scatter': {
      id: '/scatter'
      path: '/scatter'
      fullPath: '/scatter'
      preLoaderRoute: typeof ScatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScatterRoute: ScatterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
